repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.13.1
        args:
          - --line-length
          - "79"
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args:
          - --max-line-length
          - "79"
          - --extend-select
          - B950
          - --extend-ignore
          - E203,E501,E701
        additional_dependencies:
          - flake8-bugbear