---
solver:
  logging:
    logging_dir: /Users/mcmehrtens/src/fw-h-solver/log
    log_file_timestamp: "%Y%m%d-%H.%M.%S"
  input:
    input_file: /Users/mcmehrtens/src/fw-h-solver/input/20241210-03.02.41-fw-h.npz
  output:
    output_dir: /Users/mcmehrtens/src/fw-h-solver/output
    output_file_timestamp: "%Y%m%d-%H.%M.%S"
source:
  centroid:
    x: 0  # [L]
    y: 0  # [L]
    z: 0  # [L]
  description: monopole
  shape: sin
  amplitude: 5e4
  frequency: 750  # [T^-1]
  constants:
    c_0: 340.2    # [L * T^-1]
    rho_0: 1.225  # [M * L^-3]
    p_0: 10.13e4  # [F * L^-2]
    T_0: 15       # [Î˜]
  time_domain:
    start_time: 0  # [T]
    end_time: 0.75  # [T]
    n: 5000
fw_h_surface:
  centroid:
    x: 0  # [L]
    y: 0  # [L]
    z: 0  # [L]
  r: 7.5  # [L]
  n: 100
observer:
  centroid:
    x: 40.1  # [L]
    y: 42.7  # [L]
    z: 31.4  # [L]
...