---
global_config:
  logging:
    logging_dir: /Users/mcmehrtens/src/fw-h-solver/log
    log_file_timestamp: "%Y%m%d-%H.%M.%S"
  output:
    output_dir: /Users/mcmehrtens/src/fw-h-solver/output
    output_file_timestamp: "%Y%m%d-%H.%M.%S"
solver:
  input:
    data_file_path: /Users/mcmehrtens/src/fw-h-solver/input/20241211-12.46.09-fw-h.npz
  constants:
    c_0: 340.2    # [L * T^-1]
    rho_0: 1.225  # [M * L^-3]
  time_steps: 2500
source:
  point:
    x: 0  # [L]
    y: 0  # [L]
    z: 0  # [L]
  description: monopole
  shape: sin
  amplitude: 5e4
  frequency: 300  # [T^-1]
  constants:
    c_0: 340.2    # [L * T^-1]
    rho_0: 1.225  # [M * L^-3]
  time_domain:
    start_time: 0  # [T]
    end_time: 0.5  # [T]
    time_steps: 2500
  fw_h_surface:
    point:
      x: 0  # [L]
      y: 0  # [L]
      z: 0  # [L]
    r: 7.5  # [L]
    n: 50
  observer:
    point:
      x: 40.1  # [L]
      y: 42.7  # [L]
      z: 31.4  # [L]
...